#ifndef _CONFIG_H
#define _CONFIG_H

#define ENABLE_COUNTERMOVES 0
#define ENABLE_FUTILITY_DEPTH 4
#define ENABLE_HISTORY 1
#define ENABLE_KILLERS 1
#define ENABLE_LMR 1
#define ENABLE_NNUE 0
#define ENABLE_NNUE_SIMD 0
#define ENABLE_NULL_MOVE_PRUNING 1
#define ENABLE_REVERSE_FUTILITY_DEPTH 4
#define ENABLE_SEE_Q_PRUNE_LOSING_CAPTURES 1
#define ENABLE_TIMER_ASPIRATION_FAILURE 1
#define ENABLE_TT_CUTOFFS 1
#define ENABLE_TT_MOVES 1

#endif
