#ifndef _CONFIG_H
#define _CONFIG_H

#define ENABLE_LMR 1
#define ENABLE_NNUE 0
#define ENABLE_NNUE_SIMD 0
#define ENABLE_NULL_MOVE_PRUNING 1
#define ENABLE_SEE_Q_PRUNE_LOSING_CAPTURES 1
#define ENABLE_TIMER_ASPIRATION_FAILURE 1

#endif
